CREATE TABLE IF NOT EXISTS todos (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    is_completed BOOLEAN DEFAULT FALSE, -- 👈 これを追加！
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
