name: CI Test

# いつ実行するか（mainブランチにpushされたとき）
on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Dockerイメージが正しくビルドできるかチェック
    - name: Build Docker Image
      run: docker build . -t test-app:latest
